import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Barlow } from "next/font/google";
import Background from "./Background";

const inter = Inter({ subsets: ["latin"] });
const barlow = Barlow({ weight: ["600", "900"], subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`text-lg ${barlow.className}`}>
                <Background />
                {children}
            </body>
        </html>
    );
}
